[phases.setup]
nixpkgs = ["ruby_3_3", "postgresql", "openssl"]

[phases.install]
cmds = ["bundle install"]

[phases.build]
cmds = ["bundle exec rails assets:precompile"]

[start]
cmd = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"