databases:
  - name: excelapp-postgres
    databaseName: excelapp_production
    user: excelapp
    region: singapore

services:
  - type: web
    name: excelapp-rails
    env: ruby
    region: singapore
    plan: starter
    buildCommand: "export SECRET_KEY_BASE=${SECRET_KEY_BASE:-\"temp_$(date +%s)\"}; bundle install; bundle exec rails db:migrate; bundle exec rails tailwindcss:build; bundle exec rails assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    buildFilter:
      paths:
      - bin/render-build.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: excelapp-postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RUBY_VERSION
        value: 3.4.4
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY_BASE
        value: "hardcoded_secret_key_base_for_production_deployment_fix_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-southeast-1
      - key: AWS_S3_BUCKET
        sync: false
      - key: TOSS_CLIENT_KEY
        sync: false
      - key: TOSS_SECRET_KEY
        sync: false
      - key: REDIS_URL
        sync: false

  - type: worker
    name: excelapp-worker
    env: ruby
    region: singapore
    plan: starter
    buildCommand: "export SECRET_KEY_BASE=${SECRET_KEY_BASE:-\"temp_$(date +%s)\"}; bundle install; bundle exec rails db:migrate; bundle exec rails tailwindcss:build; bundle exec rails assets:precompile"
    startCommand: "bundle exec solid_queue:start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: excelapp-postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RUBY_VERSION
        value: 3.4.4
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SECRET_KEY_BASE
        value: "hardcoded_secret_key_base_for_production_deployment_fix_12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-southeast-1
      - key: AWS_S3_BUCKET
        sync: false
      - key: REDIS_URL
        sync: false