[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3002"
MAX_SESSIONS = "100"
SESSION_TIMEOUT_MS = "600000"
CLEANUP_INTERVAL_MS = "300000"