default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    # Default worker for general tasks
    - queues: ["default", "mailers"]
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    # Excel processing worker
    - queues: ["excel_processing"]
      threads: 2
      processes: <%= ENV.fetch("EXCEL_JOB_CONCURRENCY", 2) %>
      polling_interval: 0.5
    # AI analysis worker
    - queues: ["ai_analysis"]
      threads: 1
      processes: <%= ENV.fetch("AI_JOB_CONCURRENCY", 1) %>
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
